### ISSUE TITLE
TODO (未完成)

### ISSUE THREAD

**Issue by AKclown** [AKclown/js-to-ts#2]
期待您的参与（Looking forward to your participation）

**Comment by AKclown** [comment]
There are known issues that are being fixed（有已知问题正在修复）

**Comment by AKclown** [comment]
Optimizing（优化中）

**Comment by AKclown** [comment]
TODO
功能：
**高优先级：**
- [x]  支持swagger的schema数据转为TS类型
- [x]  curl命令解析请求（剪切板内容判断即可）
- [ ] 支持单个`json schema`转换、指定`schema`文档某个路径转换
- [ ] 判断类型可重用方法优化 （重写）
- [x] 联合类型兼容问题 v0.7.0
![image](https://github.com/AKclown/js-to-ts/assets/33648653/57f9454d-76d3-4bc0-9168-0ee9dcee6b08)

**低优先级：**
- [x] 引用自身（self call）
- [ ] 新增严格模式 | 非严格模式配置。针对前面一点 （严格模式已支持）
- [ ] API结果显示面板集成codemirror或者Monaco实现语法高亮 
- [ ] 类型之间添加空行
- [ ] 支持多选择区域转换

- [x] [按照映射来实现
](https://github.com/MariusAlch/vscode-json-to-ts/issues/14)
- [ ] 添加测试用例
- [ ] [增加生成类型的顺序](https://github.com/MariusAlch/vscode-json-to-ts/issues/10)
- [ ] 数组对象最外层加个[]
- [x] 剪切板判断是否为curl请求
- [x] 联合类型如果其中一个是undefined，那么应该将属性变为可选即可`{a: string | undefined }`改为`{a?: string }`
- [x] 对类型进行字符排序，例如`string | number` 与 `number | string`应该是等价的
![image](https://github.com/AKclown/js-to-ts/assets/33648653/1819b3c6-98ee-4b48-b184-2901421d0799)
- [ ] 使用curl展示403错误码
![image](https://github.com/AKclown/js-to-ts/assets/33648653/310208dc-6b57-4555-9533-3f72e6e2b176)
- [x] Swagger类型，新增具体路径类型导出选项
 
项目:
- [ ]  添加测试用例
- [ ]  添加CICD自动化
- [ ] 采用`webpack`进行构建打包优化
- [ ]  拆包

**Comment by leedalei** [comment]
左侧的那个api发送的配置感觉过分冗余了，我觉得一个输入框就够了，给用户复制fetch的字符串或者curl命令（谷歌开发者工具右键请求可以直接复制这些信息），我们从这个字符串里提取参数，再请求一次就行了，如果你觉得ok，我可以改一下提个mr

**Comment by AKclown** [comment]
> 左侧的那个api发送的配置感觉过分冗余了，我觉得一个输入框就够了，给用户复制fetch的字符串或者curl命令（谷歌开发者工具右键请求可以直接复制这些信息），我们从这个字符串里提取参数，再请求一次就行了，如果你觉得ok，我可以改一下提个mr

嗯嗯，合理的，我之前分析了`json2ts`和`json to ts`的是有该功能的。如果你有时间可以提个PR（感谢），不过`API TO TS`面板我希望保留吧（使用起来虽然比较繁琐但比较简单）
- [x] curl命令解析请求
